[tool.poetry]
name = "selenium-example"
version = "0.1.0"
description = "Code example for selenium in python"
authors = ["demerara151 <demeraraonfire@gmail.com>"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
selenium = "^4.12.0"
webdriver-manager = "^3.9.1"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
black = "^23.0.0"
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
